version: "3.9"

volumes:
  database:

networks:
  net-db:
    driver: bridge
  net-mail:
    driver: bridge
  nginx-proxy:
    name: nginx-proxy

services:
  nginx:
    build:
      context: .docker/nginx
      dockerfile: nginx.dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION}"
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: "${APP_BASE_DOMAIN}.mink.test"
      VIRTUAL_PORT: 80
      ENABLE_IPV6: true
      CERT_NAME: mink
    volumes:
      - .:/var/www/html
    networks:
      - net-db
      - nginx-proxy

  php:
    build:
      context: .docker/php
      dockerfile: php.dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION}"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - net-db
      - net-mail

  db:
    image: mysql:8
    platform: linux/x86_64
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - database:/var/lib/mysql
    networks:
      - net-db

  phpmyadmin:
    image: phpmyadmin
    env_file:
      - .env
    environment:
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      VIRTUAL_HOST: "${APP_BASE_DOMAIN}.pma.mink.test"
      VIRTUAL_PORT: 80
      ENABLE_IPV6: true
      CERT_NAME: mink
    networks:
      - net-db
      - nginx-proxy


  mailhog:
    image: mailhog/mailhog
    env_file:
      - .env
    logging:
      driver: 'none'  # disable saving logs
    environment:
      VIRTUAL_HOST: "${APP_BASE_DOMAIN}.mailhog.mink.test"
      VIRTUAL_PORT: 8025
      ENABLE_IPV6: true
      CERT_NAME: mink
    networks:
      - net-mail
      - nginx-proxy
